/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sauli' at '25/12/16 10:41' with Gradle 2.14.1
 *
 * @author sauli, @date 25/12/16 10:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
